#!/bin/bash

echo "php bin_sh"

# Vérifie si Docker Compose est installé
if ! command -v docker-compose &>/dev/null && ! command -v docker compose &>/dev/null; then
    echo "Erreur : Docker Compose n'est pas installé ou n'est pas dans le PATH."
    exit 1
fi

# Utiliser "docker compose" si disponible, sinon "docker-compose"
DOCKER_COMPOSE_CMD=$(command -v docker-compose &>/dev/null && echo "docker-compose" || echo "docker compose")

# Vérifie si un argument a été passé
if [ $# -lt 1 ]; then
    # Aucun argument passé, on lance PHPUnit sans arguments
    COMMAND="$DOCKER_COMPOSE_CMD exec php php bin/phpunit"
else
    # Si un argument est passé, on ajoute "tests/" en préfixe si nécessaire
    INPUT_PATH="$1"
    if [[ "$INPUT_PATH" != tests/* ]]; then
        INPUT_PATH="tests/$INPUT_PATH"
    fi

    # Supprime le premier argument pour reconstruire la commande avec les autres (si nécessaires)
    shift
    ADDITIONAL_ARGS="$@"

    # Crée la commande à exécuter
    COMMAND="$DOCKER_COMPOSE_CMD exec php php bin/phpunit $INPUT_PATH $ADDITIONAL_ARGS"
fi

# Affiche la commande en vert
echo -e "\033[32m$COMMAND\033[0m"

# Exécute la commande
$COMMAND
