#config/services.yaml
imports:
    - { resource: repositories.yaml }
    - { resource: eventListeners.yaml }

parameters:
    env(ADMIN_PASSWORD): '%env(ADMIN_PASSWORD)%'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        
    twig.extension.intl:
        class: Twig\Extra\Intl\IntlExtension
        tags: [ 'twig.extension' ]

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    Repas\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    Repas\User\Infrastructure\Http\Controller\:
        resource: '../src/User/Infrastructure/Http/Controller/'
        tags: [ 'controller.service_arguments' ]
    
    Repas\Command\ResetDatabaseCommand:
        tags: ['console.command']
        
    Repas\Shared\Application\Service\QueryBus:
        arguments:
            $messageBus: '@messenger.bus.default'

    Repas\User\Domain\Service\UserChecker: ~
    
